export const C = {
    ADD_NAME: "ADD_NAME",
    ADD_ANSWER: "ADD_ANSWER",
    RAISE_SCORE: "RAISE_SCORE",
    REDUCE_SCORE: "REDUCE_SCORE",
    TERMINATE_DEADLINE: "TERMINATE_DEADLINE",
    RESTART_DEADLINE: "RESTART_DEADLINE",
    SHIFT_INDICATOR: "SHIFT_INDICATOR",
    RESET_INDICATOR: "RESET_INDICATOR"
}